[project]
name = "default"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "a5chin" }
]
dependencies = [
    "fastapi>=0.111.0",
]
readme = "README.md"
requires-python = ">= 3.12"

[tool.rye]
managed = true
dev-dependencies = [
    "pytest>=8.2.2",
    "pre-commit>=3.7.0",
    "ruff>=0.4.7",
]
